name: Changesets
description: A GitHub action to automate releases with Changesets
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  publish:
    description: 'The command to use to build and publish packages'
    required: false
  userName:
    description: 'The github user used to create the version packages commit'
    required: false
  email:
    description: 'The github email used to create the version packages commit'
    required: false
branding:
  icon: 'package'
  color: 'blue'
